# Generated by ChatGPT 4.0 on April 29, 2024.
# Modified by Alexander Torres on 4.29.24 to fix syntax errors and improve readability.
# Additional comments by Alexander Torres and ChatGPT 4.0.

"""
Returns true or false, depending upon whether the system was able to grab a coaster successfully or not. 

This module provides functionality to check the success of a picking operation using a TOF sensor.
The check is based on the assumption that a successful pick will significantly reduce the distance
measured by the sensor due to the proximity of the object.

Function:
- checkSensor(): Returns True if the sensor reading post-pick is less than 10 mm, indicating a successful pick.

Example usage: 

#your cool code
   if not checkSensor(): #This handy line of code should allow us to know 
            raise RunTimeError("Your informative error message goes here.")
            
#If the sensor check fails, stop execution and output an error. You can also do other stuff when you get a "false" flag, but this example just executes a break as basic error handling. 

Happy picking! 
- Alexander T. 
"""

from TOFSensorModule import get_sensor_height

def pickStatus():
    """
    Checks if a pick operation was successful by measuring the distance to the object.
    If the distance is less than 10mm, it is assumed the pick was successful.

    Returns:
    - bool: True if the pick was successful, False otherwise.
    """
    sensor_threshold = 10  # mm
    measured_height = get_sensor_height()
    
    if measured_height < sensor_threshold:
        return True
    else:
        print(f"Sensor reading is {measured_height}mm - above missed pick threshold of {sensor_threshold}mm. Returning False.")
        return False

# Optional testing block
if __name__ == "__main__":
    result = pickStatus()
    print("Pick success:", result)


